insert into agrids.dbo.lcc_dashboard_info_scopes_new
values ('OTHER','ADD-ON CITIES WILLAMS','MUN','SANTASUSANNA','SANTA SUSANNA',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('OTHER','ADD-ON CITIES WILLIAMS','MUN','TALAMANCADEJARAMA','TALAMANCA DE JARAMA',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('OTHER','ADD-ON CITIES WILLIAMS','MUN','VALDETORRESDEJARAMA','VALDETORRES DE JARAMA',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('OTHER','ADD-ON CITIES WILLIAMS','MUN','CASTELLBELLIELVILAR','CASTELLBELL I EL VILAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('OTHER','ADD-ON CITIES WILLIAMS','MUN','COLLBATO','COLLBATÓ',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('OTHER','ADD-ON CITIES WILLIAMS','MUN','VILLACONEJOS','VILLACONEJOS',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('OTHER','ADD-ON CITIES WILLIAMS','MUN','MONISTROLDEMONTSERRAT','MONISTROL DE MONTSERRAT',NULL,NULL,NULL,NULL,NULL,NULL,NULL)


insert into agrids_v2.dbo.lcc_ciudades_tipo_project_v9
values('8261','Santa Susanna','3323',NULL,NULL,NULL,NULL,NULL,NULL,'Williams Cobertura + Calidad','P1',NULL,NULL,'ROC/ADD - Williams Calidad','SANTASUSANNA','41.5259','1.65843','BARCELONA','Zona2','Zona2','CATALUNYA','Sharing VF','ADD-ON CITIES WILLIAMS','Huawei','Ericsson','Ericsson','','1K-25K','1K-5K'),
('28145','Talamanca de Jarama','3451',NULL,NULL,NULL,NULL,NULL,NULL,'Williams Cobertura + Calidad','P1',NULL,NULL,'ROC/ADD - Williams Calidad','TALAMANCADEJARAMA','40.3697','-3.22149','MADRID','Zona1','Zona1','MADRID','Sharing VF','ADD-ON CITIES WILLIAMS','Huawei','Ericsson','Ericsson','','1K-25K','1K-5K'),
('28164','Valdetorres de Jarama','4260',NULL,NULL,NULL,NULL,NULL,NULL,'Williams Cobertura + Calidad','P1',NULL,NULL,'ROC/ADD - Williams Calidad','VALDETORRESDEJARAMA','40.3697','-3.22149','MADRID','Zona1','Zona1','MADRID','Sharing VF','ADD-ON CITIES WILLIAMS','Huawei','Ericsson','Ericsson','','1K-25K','1K-5K'),
('08053','Castellbell i el Vilar','3584',NULL,NULL,NULL,NULL,NULL,NULL,'Williams Cobertura + Calidad','P1',NULL,NULL,'ROC/ADD - Williams Calidad','CASTELLBELLIELVILAR','41.5259','1.65843','BARCELONA','Zona2','Zona2','CATALUNYA','Sharing VF','ADD-ON CITIES WILLIAMS','Huawei','Ericsson','Ericsson','','1K-25K','1K-5K'),
('08069','Collbató','4396',NULL,NULL,NULL,NULL,NULL,NULL,'Williams Cobertura + Calidad','P1',NULL,NULL,'ROC/ADD - Williams Calidad','COLLBATO','41.5259','1.65843','BARCELONA','Zona2','Zona2','CATALUNYA','Sharing VF','ADD-ON CITIES WILLIAMS','Huawei','Ericsson','Ericsson','','1K-25K','1K-5K'),
('28170','Villaconejos','3350',NULL,NULL,NULL,NULL,NULL,NULL,'Williams Cobertura + Calidad','P1',NULL,NULL,'ROC/ADD - Williams Calidad','VILLACONEJOS','40.3697','-3.22149','MADRID','Zona1','Zona1','MADRID','Sharing VF','ADD-ON CITIES WILLIAMS','Huawei','Ericsson','Ericsson','','1K-25K','1K-5K'),
('08127','Monistrol de Montserrat','2867',NULL,NULL,NULL,NULL,NULL,NULL,'Williams Cobertura + Calidad','P1',NULL,NULL,'ROC/ADD - Williams Calidad','MONISTROLDEMONTSERRAT','41.5259','1.65843','BARCELONA','Zona2','Zona2','CATALUNYA','Sharing VF','ADD-ON CITIES WILLIAMS','Huawei','Ericsson','Ericsson','','1K-25K','1K-5K')

