--Renombrar Bases de datos

USE master;  

ALTER DATABASE FY1617_Data_Badajoz_3G_H2
SET SINGLE_USER WITH ROLLBACK IMMEDIATE

ALTER DATABASE FY1617_Data_Badajoz_3G_H2 MODIFY NAME = FY1617_Data_Smaller_3G_H2_6

ALTER DATABASE FY1617_Data_Smaller_3G_H2_6
SET MULTI_USER WITH ROLLBACK IMMEDIATE