--Renombrar Bases de datos

USE master;  

ALTER DATABASE FY1718_DATA_ZARAGOZA_4G_H1
SET SINGLE_USER WITH ROLLBACK IMMEDIATE

ALTER DATABASE FY1718_DATA_ZARAGOZA_4G_H1 MODIFY NAME = FY1718_DATA_ZARAGOZA_4G_H1_1

ALTER DATABASE FY1718_DATA_ZARAGOZA_4G_H1_1
SET MULTI_USER WITH ROLLBACK IMMEDIATE

