declare @cmd nvarchar(4000)				
DECLARE @nameTabla varchar(256)							
DECLARE @pattern varchar(256) = 'AGGRData4G'
DECLARE @sheet varchar(256) = '_4GDevice'

DECLARE @nameBD varchar(256)				
declare @it2 bigint				
declare @MaxBBDD bigint				
declare @it1 bigint				
declare @MaxTab bigint				
				
set @it1 = 1				
set @it2 = 1				
				
exec sp_lcc_dropifexists '_tmp_BBDD'				
				
select IDENTITY(int,1,1) id,name				
into _tmp_BBDD				
from sys.databases				
where name like  @pattern	
	and name not like '%_old' --and name <> 'FY1617_Voice_AVE_MAD_BCN_H2'
				
select @MaxBBDD = MAX(id) 				
from _tmp_BBDD				
				
while @it2 <= @MaxBBDD	
begin				
				
	select @nameBD = name			
	from _tmp_BBDD			
	where id =@it2			
	print 'Nombre de la bbdd:  ' + @nameBD			
		
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_DL_Thput_NC'+@sheet+' ADD [Count_Throughput_384k] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_UL_Thput_NC'+@sheet+' ADD [Count_Throughput_384k] [int] NULL' exec(@cmd)


set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Reproducciones_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Fails_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Time To First Image_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Time To First Image max_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Num. Interruptions_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [ReproduccionesSinInt_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [ReproduccionesHD_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count_Video_Resolucion_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count_Video_MOS_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Service success ratio W/o interruptions_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Reproduction ratio W/o interruptions_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Successful video download_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [avg video resolution_Video1] [varchar](256) NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [B4_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [video mos_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [url_Video1] [varchar](256) NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [1st Resolution_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 1st Resolution_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [2nd Resolution_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 2nd Resolution_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [FirstChangeFromInit_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count FirstChangeFromInit_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [initialResolution_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count initialResolution_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [finalResolution_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count finalResolution_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Duration_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count Duration_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [144p-VideoDuration_Video1] [float] NULL' exec(@cmd)		
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 144p-VideoDuration_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [144p-VideoMOS_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 144p-VideoMOS_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 144p_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 144p_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [240p-VideoDuration_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 240p-VideoDuration_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [240p-VideoMOS_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 240p-VideoMOS_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 240p_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 240p_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [360p-VideoDuration_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 360p-VideoDuration_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [360p-VideoMOS_Video1] [float] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 360p-VideoMOS_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 360p_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 360p_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [480p-VideoDuration_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 480p-VideoDuration_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [480p-VideoMOS_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 480p-VideoMOS_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 480p_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 480p_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [720p-VideoDuration_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 720p-VideoDuration_Video1] [int] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [720p-VideoMOS_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 720p-VideoMOS_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 720p_Video1] [float] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 720p_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [1080p-VideoDuration_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 1080p-VideoDuration_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [1080p-VideoMOS_Video1] [float] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 1080p-VideoMOS_Video1] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 1080p_Video1] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 1080p_Video1] [int] NULL' exec(@cmd)

set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Reproducciones_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Fails_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Time To First Image_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Time To First Image max_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Num. Interruptions_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [ReproduccionesSinInt_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [ReproduccionesHD_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count_Video_Resolucion_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count_Video_MOS_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Service success ratio W/o interruptions_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Reproduction ratio W/o interruptions_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Successful video download_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [avg video resolution_Video2] [varchar](256) NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [B4_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [video mos_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [url_Video2] [varchar](256) NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [1st Resolution_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 1st Resolution_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [2nd Resolution_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 2nd Resolution_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [FirstChangeFromInit_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count FirstChangeFromInit_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [initialResolution_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count initialResolution_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [finalResolution_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count finalResolution_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Duration_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count Duration_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [144p-VideoDuration_Video2] [float] NULL' exec(@cmd)		
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 144p-VideoDuration_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [144p-VideoMOS_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 144p-VideoMOS_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 144p_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 144p_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [240p-VideoDuration_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 240p-VideoDuration_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [240p-VideoMOS_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 240p-VideoMOS_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 240p_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 240p_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [360p-VideoDuration_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 360p-VideoDuration_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [360p-VideoMOS_Video2] [float] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 360p-VideoMOS_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 360p_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 360p_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [480p-VideoDuration_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 480p-VideoDuration_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [480p-VideoMOS_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 480p-VideoMOS_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 480p_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 480p_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [720p-VideoDuration_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 720p-VideoDuration_Video2] [int] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [720p-VideoMOS_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 720p-VideoMOS_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 720p_Video2] [float] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 720p_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [1080p-VideoDuration_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 1080p-VideoDuration_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [1080p-VideoMOS_Video2] [float] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 1080p-VideoMOS_Video2] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 1080p_Video2] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 1080p_Video2] [int] NULL' exec(@cmd)

set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Reproducciones_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Fails_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Time To First Image_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Time To First Image max_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Num. Interruptions_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [ReproduccionesSinInt_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [ReproduccionesHD_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count_Video_Resolucion_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count_Video_MOS_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Service success ratio W/o interruptions_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Reproduction ratio W/o interruptions_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Successful video download_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [avg video resolution_Video3] [varchar](256) NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [B4_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [video mos_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [url_Video3] [varchar](256) NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [1st Resolution_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 1st Resolution_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [2nd Resolution_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 2nd Resolution_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [FirstChangeFromInit_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count FirstChangeFromInit_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [initialResolution_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count initialResolution_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [finalResolution_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count finalResolution_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Duration_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count Duration_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [144p-VideoDuration_Video3] [float] NULL' exec(@cmd)		
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 144p-VideoDuration_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [144p-VideoMOS_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 144p-VideoMOS_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 144p_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 144p_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [240p-VideoDuration_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 240p-VideoDuration_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [240p-VideoMOS_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 240p-VideoMOS_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 240p_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 240p_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [360p-VideoDuration_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 360p-VideoDuration_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [360p-VideoMOS_Video3] [float] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 360p-VideoMOS_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 360p_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 360p_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [480p-VideoDuration_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 480p-VideoDuration_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [480p-VideoMOS_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 480p-VideoMOS_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 480p_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 480p_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [720p-VideoDuration_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 720p-VideoDuration_Video3] [int] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [720p-VideoMOS_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 720p-VideoMOS_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 720p_Video3] [float] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 720p_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [1080p-VideoDuration_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 1080p-VideoDuration_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [1080p-VideoMOS_Video3] [float] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 1080p-VideoMOS_Video3] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 1080p_Video3] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 1080p_Video3] [int] NULL' exec(@cmd)

set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Reproducciones_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Fails_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Time To First Image_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Time To First Image max_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Num. Interruptions_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [ReproduccionesSinInt_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [ReproduccionesHD_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count_Video_Resolucion_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count_Video_MOS_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Service success ratio W/o interruptions_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Reproduction ratio W/o interruptions_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Successful video download_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [avg video resolution_Video4] [varchar](256) NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [B4_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [video mos_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [url_Video4] [varchar](256) NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [1st Resolution_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 1st Resolution_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [2nd Resolution_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 2nd Resolution_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [FirstChangeFromInit_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count FirstChangeFromInit_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [initialResolution_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count initialResolution_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [finalResolution_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count finalResolution_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Duration_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count Duration_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [144p-VideoDuration_Video4] [float] NULL' exec(@cmd)		
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 144p-VideoDuration_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [144p-VideoMOS_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 144p-VideoMOS_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 144p_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 144p_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [240p-VideoDuration_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 240p-VideoDuration_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [240p-VideoMOS_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 240p-VideoMOS_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 240p_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 240p_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [360p-VideoDuration_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 360p-VideoDuration_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [360p-VideoMOS_Video4] [float] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 360p-VideoMOS_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 360p_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 360p_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [480p-VideoDuration_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 480p-VideoDuration_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [480p-VideoMOS_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 480p-VideoMOS_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 480p_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 480p_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [720p-VideoDuration_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 720p-VideoDuration_Video4] [int] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [720p-VideoMOS_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 720p-VideoMOS_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 720p_Video4] [float] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 720p_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [1080p-VideoDuration_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 1080p-VideoDuration_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [1080p-VideoMOS_Video4] [float] NULL' exec(@cmd)	
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count 1080p-VideoMOS_Video4] [int] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [% 1080p_Video4] [float] NULL' exec(@cmd)
set @cmd = 'ALTER TABLE '+@nameBD +'.dbo.lcc_aggr_sp_MDD_Data_Youtube_HD'+@sheet+' ADD [Count % 1080p_Video4] [int] NULL' exec(@cmd)

				
	set @it2 = @it2 +1			
end				
				
				
exec sp_lcc_dropifexists '_tmp_BBDD'	